/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateDocumentRouteImport } from './routes/createDocument'
import { Route as VersionsIndexRouteImport } from './routes/versions/index'
import { Route as VersionsTeamRouteImport } from './routes/versions/team'
import { Route as VersionsRejectedRouteImport } from './routes/versions/rejected'
import { Route as VersionsPendingRouteImport } from './routes/versions/pending'
import { Route as VersionsDraftsRouteImport } from './routes/versions/drafts'
import { Route as VersionsApprovedRouteImport } from './routes/versions/approved'
import { Route as DocumentsDocIdVersionsVersionIdRouteImport } from './routes/documents/$docId/versions.$versionId'

const RegisterLazyRouteImport = createFileRoute('/register')()
const ManageUsersLazyRouteImport = createFileRoute('/manageUsers')()
const LoginLazyRouteImport = createFileRoute('/login')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const DocumentsIndexLazyRouteImport = createFileRoute('/documents/')()
const DocumentsDocIdIndexLazyRouteImport =
  createFileRoute('/documents/$docId/')()
const DocumentsDocIdEditLazyRouteImport = createFileRoute(
  '/documents/$docId/edit',
)()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const ManageUsersLazyRoute = ManageUsersLazyRouteImport.update({
  id: '/manageUsers',
  path: '/manageUsers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/manageUsers.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const CreateDocumentRoute = CreateDocumentRouteImport.update({
  id: '/createDocument',
  path: '/createDocument',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DocumentsIndexLazyRoute = DocumentsIndexLazyRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/documents/index.lazy').then((d) => d.Route),
)
const VersionsIndexRoute = VersionsIndexRouteImport.update({
  id: '/versions/',
  path: '/versions/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsTeamRoute = VersionsTeamRouteImport.update({
  id: '/versions/team',
  path: '/versions/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsRejectedRoute = VersionsRejectedRouteImport.update({
  id: '/versions/rejected',
  path: '/versions/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsPendingRoute = VersionsPendingRouteImport.update({
  id: '/versions/pending',
  path: '/versions/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsDraftsRoute = VersionsDraftsRouteImport.update({
  id: '/versions/drafts',
  path: '/versions/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsApprovedRoute = VersionsApprovedRouteImport.update({
  id: '/versions/approved',
  path: '/versions/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocIdIndexLazyRoute = DocumentsDocIdIndexLazyRouteImport.update({
  id: '/documents/$docId/',
  path: '/documents/$docId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/documents/$docId/index.lazy').then((d) => d.Route),
)
const DocumentsDocIdEditLazyRoute = DocumentsDocIdEditLazyRouteImport.update({
  id: '/documents/$docId/edit',
  path: '/documents/$docId/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/documents/$docId/edit.lazy').then((d) => d.Route),
)
const DocumentsDocIdVersionsVersionIdRoute =
  DocumentsDocIdVersionsVersionIdRouteImport.update({
    id: '/documents/$docId/versions/$versionId',
    path: '/documents/$docId/versions/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/createDocument': typeof CreateDocumentRoute
  '/dashboard': typeof DashboardLazyRoute
  '/login': typeof LoginLazyRoute
  '/manageUsers': typeof ManageUsersLazyRoute
  '/register': typeof RegisterLazyRoute
  '/versions/approved': typeof VersionsApprovedRoute
  '/versions/drafts': typeof VersionsDraftsRoute
  '/versions/pending': typeof VersionsPendingRoute
  '/versions/rejected': typeof VersionsRejectedRoute
  '/versions/team': typeof VersionsTeamRoute
  '/versions/': typeof VersionsIndexRoute
  '/documents/': typeof DocumentsIndexLazyRoute
  '/documents/$docId/edit': typeof DocumentsDocIdEditLazyRoute
  '/documents/$docId/': typeof DocumentsDocIdIndexLazyRoute
  '/documents/$docId/versions/$versionId': typeof DocumentsDocIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/createDocument': typeof CreateDocumentRoute
  '/dashboard': typeof DashboardLazyRoute
  '/login': typeof LoginLazyRoute
  '/manageUsers': typeof ManageUsersLazyRoute
  '/register': typeof RegisterLazyRoute
  '/versions/approved': typeof VersionsApprovedRoute
  '/versions/drafts': typeof VersionsDraftsRoute
  '/versions/pending': typeof VersionsPendingRoute
  '/versions/rejected': typeof VersionsRejectedRoute
  '/versions/team': typeof VersionsTeamRoute
  '/versions': typeof VersionsIndexRoute
  '/documents': typeof DocumentsIndexLazyRoute
  '/documents/$docId/edit': typeof DocumentsDocIdEditLazyRoute
  '/documents/$docId': typeof DocumentsDocIdIndexLazyRoute
  '/documents/$docId/versions/$versionId': typeof DocumentsDocIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/createDocument': typeof CreateDocumentRoute
  '/dashboard': typeof DashboardLazyRoute
  '/login': typeof LoginLazyRoute
  '/manageUsers': typeof ManageUsersLazyRoute
  '/register': typeof RegisterLazyRoute
  '/versions/approved': typeof VersionsApprovedRoute
  '/versions/drafts': typeof VersionsDraftsRoute
  '/versions/pending': typeof VersionsPendingRoute
  '/versions/rejected': typeof VersionsRejectedRoute
  '/versions/team': typeof VersionsTeamRoute
  '/versions/': typeof VersionsIndexRoute
  '/documents/': typeof DocumentsIndexLazyRoute
  '/documents/$docId/edit': typeof DocumentsDocIdEditLazyRoute
  '/documents/$docId/': typeof DocumentsDocIdIndexLazyRoute
  '/documents/$docId/versions/$versionId': typeof DocumentsDocIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/createDocument'
    | '/dashboard'
    | '/login'
    | '/manageUsers'
    | '/register'
    | '/versions/approved'
    | '/versions/drafts'
    | '/versions/pending'
    | '/versions/rejected'
    | '/versions/team'
    | '/versions/'
    | '/documents/'
    | '/documents/$docId/edit'
    | '/documents/$docId/'
    | '/documents/$docId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/createDocument'
    | '/dashboard'
    | '/login'
    | '/manageUsers'
    | '/register'
    | '/versions/approved'
    | '/versions/drafts'
    | '/versions/pending'
    | '/versions/rejected'
    | '/versions/team'
    | '/versions'
    | '/documents'
    | '/documents/$docId/edit'
    | '/documents/$docId'
    | '/documents/$docId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/createDocument'
    | '/dashboard'
    | '/login'
    | '/manageUsers'
    | '/register'
    | '/versions/approved'
    | '/versions/drafts'
    | '/versions/pending'
    | '/versions/rejected'
    | '/versions/team'
    | '/versions/'
    | '/documents/'
    | '/documents/$docId/edit'
    | '/documents/$docId/'
    | '/documents/$docId/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CreateDocumentRoute: typeof CreateDocumentRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ManageUsersLazyRoute: typeof ManageUsersLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  VersionsApprovedRoute: typeof VersionsApprovedRoute
  VersionsDraftsRoute: typeof VersionsDraftsRoute
  VersionsPendingRoute: typeof VersionsPendingRoute
  VersionsRejectedRoute: typeof VersionsRejectedRoute
  VersionsTeamRoute: typeof VersionsTeamRoute
  VersionsIndexRoute: typeof VersionsIndexRoute
  DocumentsIndexLazyRoute: typeof DocumentsIndexLazyRoute
  DocumentsDocIdEditLazyRoute: typeof DocumentsDocIdEditLazyRoute
  DocumentsDocIdIndexLazyRoute: typeof DocumentsDocIdIndexLazyRoute
  DocumentsDocIdVersionsVersionIdRoute: typeof DocumentsDocIdVersionsVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manageUsers': {
      id: '/manageUsers'
      path: '/manageUsers'
      fullPath: '/manageUsers'
      preLoaderRoute: typeof ManageUsersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createDocument': {
      id: '/createDocument'
      path: '/createDocument'
      fullPath: '/createDocument'
      preLoaderRoute: typeof CreateDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/': {
      id: '/versions/'
      path: '/versions'
      fullPath: '/versions/'
      preLoaderRoute: typeof VersionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/team': {
      id: '/versions/team'
      path: '/versions/team'
      fullPath: '/versions/team'
      preLoaderRoute: typeof VersionsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/rejected': {
      id: '/versions/rejected'
      path: '/versions/rejected'
      fullPath: '/versions/rejected'
      preLoaderRoute: typeof VersionsRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/pending': {
      id: '/versions/pending'
      path: '/versions/pending'
      fullPath: '/versions/pending'
      preLoaderRoute: typeof VersionsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/drafts': {
      id: '/versions/drafts'
      path: '/versions/drafts'
      fullPath: '/versions/drafts'
      preLoaderRoute: typeof VersionsDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/approved': {
      id: '/versions/approved'
      path: '/versions/approved'
      fullPath: '/versions/approved'
      preLoaderRoute: typeof VersionsApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId/': {
      id: '/documents/$docId/'
      path: '/documents/$docId'
      fullPath: '/documents/$docId/'
      preLoaderRoute: typeof DocumentsDocIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId/edit': {
      id: '/documents/$docId/edit'
      path: '/documents/$docId/edit'
      fullPath: '/documents/$docId/edit'
      preLoaderRoute: typeof DocumentsDocIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId/versions/$versionId': {
      id: '/documents/$docId/versions/$versionId'
      path: '/documents/$docId/versions/$versionId'
      fullPath: '/documents/$docId/versions/$versionId'
      preLoaderRoute: typeof DocumentsDocIdVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreateDocumentRoute: CreateDocumentRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ManageUsersLazyRoute: ManageUsersLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  VersionsApprovedRoute: VersionsApprovedRoute,
  VersionsDraftsRoute: VersionsDraftsRoute,
  VersionsPendingRoute: VersionsPendingRoute,
  VersionsRejectedRoute: VersionsRejectedRoute,
  VersionsTeamRoute: VersionsTeamRoute,
  VersionsIndexRoute: VersionsIndexRoute,
  DocumentsIndexLazyRoute: DocumentsIndexLazyRoute,
  DocumentsDocIdEditLazyRoute: DocumentsDocIdEditLazyRoute,
  DocumentsDocIdIndexLazyRoute: DocumentsDocIdIndexLazyRoute,
  DocumentsDocIdVersionsVersionIdRoute: DocumentsDocIdVersionsVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
